language: php

php:
  - 7.4

services:
  - redis-server

before_script:
  - cp .env.travis .env
  - composer install --no-interaction
  - php artisan key:generate

script:
  - vendor/bin/phpunit

cache:
  directories:
    - vendor
