language: php

php:
  - 7.4

before_install:
  sudo service redis-server start --bind 127.0.0.1

before_script:
  - cp .env.travis .env
  - composer install --no-interaction
  - php artisan key:generate

services:
  - redis-server

script:
  - vendor/bin/phpunit

cache:
  directories:
    - vendor
